const words = {
    dico: [
            "Canada",
            "Boutique",
            "Friandise",
            "Shopping",
            "Deuxième",
            "Pyrénées",
            "Disneyland",
            "Orange",
            "Symphonie",
            "Couple",
            "Koala",
            "Circuit",
            "Cramoisi",
            "Water-polo",
            "Bourdonnement",
            "Recette",
            "Offre",
            "Sentir",
            "Souple",
            "Limace",
            "Sardine",
            "Joint",
            "Moineau",
            "Souris",
            "Tatou",
            "Cygne",
            "Dauphin",
            "Lémurien",
            "Bœuf",
            "Marron",
            "Rouge",
            "Orange",
            "Blanc",
            "Noir",
            "Marron",
            "Blanc",
            "Rose",
            "Bleu",
            "Jaune",
            "Père",
            "Cousine",
            "Gendre",
            "Nièce",
            "Nièce",
            "Cousin",
            "Oncle",
            "Poire",
            "Citron",
            "Haricots",
            "Lait",
            "Poisson",
            "Banane",
            "Orge",
            "Noisette",
            "Palourdes",
            "Carotte",
            "Sport",
            "Philologie",
            "Réalisateur",
            "Plume",
            "Journalisme",
            "Cartable",
            "Classe",
            "Lire",
            "Entreprise",
            "Motivation",
            "Industrie",
            "Captif",
            "Affiler",
            "Chant",
            "Lesbienne",
            "Militaires",
            "Irritation",
            "Premier",
            "Secondes",
            "De",
            "Crédit",
            "Narration",
            "Colère",
            "Caravelles",
            "Agiter",
            "Baleine",
            "Lutte",
            "Hallucination",
            "Antigel",
            "Arbitre",
            "Poule",
            "Bon",
            "Parapluie",
            "Neige",
            "Fourchette",
            "Route",
            "Poulet",
            "Toilettes",
            "Soldat",
            "Cinq",
            "Cloche",
            "Soldat",
            "Animal",
            "Pierre",
            "Chaussure",
            "Magasin",
            "Hiver",
            "Soldat",
            "Trois",
            "Parler",
            "Couettes",
            "Carte",
            "Guitare",
            "Magasin",
            "Valise",
            "Fille",
            "Sucette",
            "Avion",
            "Carotte",
            "Feuille",],

    randomIndex: 0,

    divGame: document.querySelector(".game"),
    currentWord: document.createElement("p"),

    init: function() {

        words.randomGeneration();

        words.wordAffichage();

    },

    randomGeneration: function() {
        words.randomIndex = Math.floor((Math.random() * words.dico.length-1) +1);
    },

    wordAffichage: function() {

        words.currentWord.remove();
        words.currentWord.classList.add("current-word");
        words.currentWord.textContent = words.dico[words.randomIndex];
        words.divGame.append(words.currentWord);

    }

}
